CREATE TABLE links (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    slug VARCHAR(10) UNIQUE NOT NULL,
    target_url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    click_count BIGINT DEFAULT 0
);